# Pomoćna bilježnica

- Dodavanje stringa na string
- Indeksiranje stringa

In [1]:
a= "bok"
b= "DAN"

In [2]:
b+= a
b

'DANbok'

In [3]:
len( b )

6

In [4]:
b[0], b[1], b[2]

('D', 'A', 'N')

In [5]:
b[0:2]

'DA'

- lista

In [6]:
dir(list)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

- indeksiranje liste

In [7]:
lista = ["bok", "DAN"]
lista

['bok', 'DAN']

In [8]:
lista[1][0:2]

'DA'

- pretraživanje unutar stringa

In [9]:
imam= "3.2."

In [10]:
naso=imam.find(".")
naso

1

In [11]:
imam[0:naso]

'3'

In [12]:
novo= imam.find(".", naso + 1)
novo

3

In [13]:
imam[naso+1:novo]

'2'

- vektor

In [14]:
import numpy as np
vektor = np.array([0]) 
vektor

array([0])

In [15]:
vector= [8, 2, 3]
vector

[8, 2, 3]

In [16]:
vector[1]= 5
vector

[8, 5, 3]

In [17]:
#UBACIVANJE NOVOG ELEMNTA U ARRAY
vektor = np.insert(vektor, 1, 1)
#vector[3]=4

vektor

array([0, 1])

In [18]:
vektor[1]

1

In [19]:
vektor[1]= vektor[1] +1
vektor[1]

2

In [20]:
vektor[1]+=1
vektor[1]

3

In [21]:
vec = np.zeros(39)
vec

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.])

In [22]:
vec[38] += 1

In [23]:
vec[38]

1.0

In [24]:
vec

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1.])

- ispis

In [25]:
i = 23
print ( 'pokusaj', '=', i)

pokusaj = 23


In [26]:
draw_number= np.zeros([39, 2], dtype=np.int64)
draw_number

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [27]:
draw_number[0]=3
draw_number

array([[3, 3],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [28]:
draw_number[0][1]=5
draw_number[0][0]=4
draw_number

array([[4, 5],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [38]:
sred = np.full(39, 1, dtype=np.int64)
sred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])